const { Connection } = require('../models');

const connectionData = [
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    },
    {
        firstName: "Lindsay",
        lastName: "Reiner",
        metAt: "",
        hometown: "",
        relationship: "",
        email: "",
        phone: "",
        address: "",
        birthday: "",
        occupation: "",
        company: "",
        partner: "",
        partnerName: "",
        anniversary: "",
        children: "",
        childName: "",
        childBirthday: "",
        pets: "",
        petName: "",
        interestsHobbies: "",
        importantDatesTitle: "",
        importantDatesDate: "",
        giftIdeas: ""
    }
];

const seedConnections = () => Connection.bulkCreate(connectionData);

module.exports = seedConnections;